// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.test.domain;

import com.sut.test.domain.ApplicationConversionServiceFactoryBean;
import com.sut.test.domain.Blabla;
import org.springframework.beans.factory.annotation.Configurable;
import org.springframework.core.convert.converter.Converter;
import org.springframework.format.FormatterRegistry;

privileged aspect ApplicationConversionServiceFactoryBean_Roo_ConversionService {
    
    declare @type: ApplicationConversionServiceFactoryBean: @Configurable;
    
    public Converter<Blabla, String> ApplicationConversionServiceFactoryBean.getBlablaToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.sut.test.domain.Blabla, java.lang.String>() {
            public String convert(Blabla blabla) {
                return "(no displayable fields)";
            }
        };
    }
    
    public Converter<Long, Blabla> ApplicationConversionServiceFactoryBean.getIdToBlablaConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.sut.test.domain.Blabla>() {
            public com.sut.test.domain.Blabla convert(java.lang.Long id) {
                return Blabla.findBlabla(id);
            }
        };
    }
    
    public Converter<String, Blabla> ApplicationConversionServiceFactoryBean.getStringToBlablaConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.sut.test.domain.Blabla>() {
            public com.sut.test.domain.Blabla convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Blabla.class);
            }
        };
    }
    
    public void ApplicationConversionServiceFactoryBean.installLabelConverters(FormatterRegistry registry) {
        registry.addConverter(getBlablaToStringConverter());
        registry.addConverter(getIdToBlablaConverter());
        registry.addConverter(getStringToBlablaConverter());
    }
    
    public void ApplicationConversionServiceFactoryBean.afterPropertiesSet() {
        super.afterPropertiesSet();
        installLabelConverters(getObject());
    }
    
}
