// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.test.domain;

import com.sut.test.domain.Blabla;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Blabla_Roo_Jpa_Entity {
    
    declare @type: Blabla: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Blabla.id;
    
    @Version
    @Column(name = "version")
    private Integer Blabla.version;
    
    public Long Blabla.getId() {
        return this.id;
    }
    
    public void Blabla.setId(Long id) {
        this.id = id;
    }
    
    public Integer Blabla.getVersion() {
        return this.version;
    }
    
    public void Blabla.setVersion(Integer version) {
        this.version = version;
    }
    
}
