// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.test.domain;

import com.sut.test.domain.Blabla;
import com.sut.test.domain.BlablaController;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect BlablaController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String BlablaController.create(@Valid Blabla blabla, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, blabla);
            return "blablas/create";
        }
        uiModel.asMap().clear();
        blabla.persist();
        return "redirect:/blablas/" + encodeUrlPathSegment(blabla.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String BlablaController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Blabla());
        return "blablas/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String BlablaController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("blabla", Blabla.findBlabla(id));
        uiModel.addAttribute("itemId", id);
        return "blablas/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String BlablaController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, @RequestParam(value = "sortFieldName", required = false) String sortFieldName, @RequestParam(value = "sortOrder", required = false) String sortOrder, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("blablas", Blabla.findBlablaEntries(firstResult, sizeNo, sortFieldName, sortOrder));
            float nrOfPages = (float) Blabla.countBlablas() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("blablas", Blabla.findAllBlablas(sortFieldName, sortOrder));
        }
        return "blablas/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String BlablaController.update(@Valid Blabla blabla, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, blabla);
            return "blablas/update";
        }
        uiModel.asMap().clear();
        blabla.merge();
        return "redirect:/blablas/" + encodeUrlPathSegment(blabla.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String BlablaController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, Blabla.findBlabla(id));
        return "blablas/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String BlablaController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Blabla blabla = Blabla.findBlabla(id);
        blabla.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/blablas";
    }
    
    void BlablaController.populateEditForm(Model uiModel, Blabla blabla) {
        uiModel.addAttribute("blabla", blabla);
    }
    
    String BlablaController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
