// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.test.domain;

import com.sut.test.domain.Blabla;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Blabla_Roo_Configurable {
    
    declare @type: Blabla: @Configurable;
    
}
