// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.test.domain;

import com.sut.test.domain.Blabla;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Blabla_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Blabla.entityManager;
    
    public static final List<String> Blabla.fieldNames4OrderClauseFilter = java.util.Arrays.asList("");
    
    public static final EntityManager Blabla.entityManager() {
        EntityManager em = new Blabla().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Blabla.countBlablas() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Blabla o", Long.class).getSingleResult();
    }
    
    public static List<Blabla> Blabla.findAllBlablas() {
        return entityManager().createQuery("SELECT o FROM Blabla o", Blabla.class).getResultList();
    }
    
    public static List<Blabla> Blabla.findAllBlablas(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Blabla o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Blabla.class).getResultList();
    }
    
    public static Blabla Blabla.findBlabla(Long id) {
        if (id == null) return null;
        return entityManager().find(Blabla.class, id);
    }
    
    public static List<Blabla> Blabla.findBlablaEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Blabla o", Blabla.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<Blabla> Blabla.findBlablaEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Blabla o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Blabla.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Blabla.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Blabla.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Blabla attached = Blabla.findBlabla(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Blabla.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Blabla.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Blabla Blabla.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Blabla merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
